### PR TITLE
Locust Example Issue

### PR DESCRIPTION
**Pull request by jossiebk**

### CODE REVIEW

**Review by cloudsociety-dev — COMMENTED** [review]
Name the file as HowToUseIt

**Comment by cloudsociety-dev** [comment]
Please rename the files and images in english and renmate the files without using spaces, and then we can merge the code. @jossiebk

**Comment by jossiebk** [comment]
Files rename into english names

**Comment by jossiebk** [comment]
@cloudsociety-dev  done.

**Pull request merged**
